### ISSUE TITLE
扑克检测有问题

### ISSUE THREAD

**Issue by tuwulin365** [ZZMarquis/nist_sts#1]
扑克检测有问题，一个全是0x00的文件，测试也ok。

**Comment by ZZMarquis** [comment]
感谢指出问题，已修复提交

**Comment by ZZMarquis** [comment]
#https://github.com/ZZMarquis/nist_sts/commit/49a9ff465b602f4d130b06160b00f5034c530b69

**Comment by wangsuo2015** [comment]
算法还是错误的哦
![image](https://user-images.githubusercontent.com/15029406/62364328-c09df080-b553-11e9-9673-b0262cbcf3dc.png)
