### ISSUE TITLE
Clone问题

### ISSUE THREAD

**Issue by YangPotatoes** [ZZMarquis/nist_sts#2]
您好，想和您请教一下，这个项目我在clone后无论是linux unzip还是windows直接解压全都解压失败，请问是什么问题

**Comment by ZZMarquis** [comment]
在git bash下执行以下命令：
git clone https://github.com/ZZMarquis/nist_sts.git

**Comment by YangPotatoes** [comment]
尝试过都不能解决，最后借助gitee搞定的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 下午4:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZZMarquis/nist_sts] Clone问题 (#2)




 
在git bash下执行以下命令：
 git clone https://github.com/ZZMarquis/nist_sts.git

**Comment by YangPotatoes** [comment]
再次对您的项目表示感谢，使用您的项目完成了对团队随机数生成算法进行了测试，学到了很多东西。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "杨贺昆"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 下午5:13
***@***.***&gt;;

主题:&nbsp;回复：[ZZMarquis/nist_sts] Clone问题 (#2)



尝试过都不能解决，最后借助gitee搞定的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 下午4:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZZMarquis/nist_sts] Clone问题 (#2)




 
在git bash下执行以下命令：
 git clone https://github.com/ZZMarquis/nist_sts.git
