### ISSUE TITLE
请问在游程分布测试和扑克测试中是否存在calloc参数顺序不当

### ISSUE THREAD

**Issue by DK-DARKmatter** [ZZMarquis/nist_sts#3]
https://github.com/ZZMarquis/nist_sts/blob/205eb8edbacfef796c4d4d7af69a80dd0ae1d986/nist_sts/pokerDetect.c#L45
https://github.com/ZZMarquis/nist_sts/blob/205eb8edbacfef796c4d4d7af69a80dd0ae1d986/nist_sts/runsDistribution.c#L15

函数calloc：
void *calloc(size_t nmemb, size_t size);
The calloc() function allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory. The memory is set to zero. If nmemb or size is 0, then calloc() returns either NULL, or a unique pointer value that can later be successfully passed to free().

前一个参数应当为元素的个数，后一个参数应当为每个元素的size大小
虽然对函数的正确性应该没影响，但是建议保持一致

**Comment by ZZMarquis** [comment]
感谢建议
